### ISSUE TITLE
cdx-indexer missing import of sys

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#161]
```pytb
$ cdx-indexer -s -p -j collections/3d-maps-minus-3d/indexes collections/3d-maps-minus-3d/archive/newyork_15.warc 
Traceback (most recent call last):
  File "/usr/local/bin/cdx-indexer", line 9, in <module>
    load_entry_point('pywb==0.11.0', 'console_scripts', 'cdx-indexer')()
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/cdxindexer.py", line 449, in main
    minimal=cmd.minimal_cdxj)
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/cdxindexer.py", line 259, in write_multi_cdx_index
    **options)
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/cdxindexer.py", line 296, in write_cdx_index
    for entry in entry_iter:
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 507, in __call__
    for entry in entry_iter:
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 382, in join_request_records
    for entry in entry_iter:
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 373, in create_record_iter
    arcv_iter.read_to_end(record, compute_digest)
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 201, in read_to_end
    self.next_line, empty_size = self._consume_blanklines()
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 161, in _consume_blanklines
    sys.stderr.write(self.INC_RECORD.format(err_offset, line))
NameError: global name 'sys' is not defined
```

**Comment by ikreymer** [comment]
Should be fixed in develop now, but send me the WARC as it indicates something is wrong with it (record truncated), want to double check that that's the case..
