### ISSUE TITLE
Errors with cdx-indexer

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#168]
I have a directory with 45k warc.gz files of around 2MB size each, that I want to make an index of. `cdx-indexer` gives the following error message:

```pycon
$ cdx-indexer -s -p -j . my-folder
Traceback (most recent call last):
  File "/usr/local/bin/cdx-indexer", line 9, in <module>
    load_entry_point('pywb==0.11.1', 'console_scripts', 'cdx-indexer')()
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/cdxindexer.py", line 449, in main
    minimal=cmd.minimal_cdxj)
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/cdxindexer.py", line 259, in write_multi_cdx_index
    **options)
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/cdxindexer.py", line 296, in write_cdx_index
    for entry in entry_iter:
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 532, in __call__
    for entry in entry_iter:
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 407, in join_request_records
    for entry in entry_iter:
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 350, in create_record_iter
    for record in arcv_iter.iter_records(block_size):
  File "/usr/local/lib/python2.7/dist-packages/pywb/warc/archiveiterator.py", line 96, in iter_records
    self.read_to_end(record)
UnboundLocalError: local variable 'record' referenced before assignment
```

This has only happened after the process ran for an extended amount of time.

**Comment by despens** [comment]
A new run with the same files resulted in a core dump after 34 minutes.

**Comment by anjackson** [comment]
This kind of behaviour seems to be consistent with the process running out of system resources, e.g. RAM or file handles or temp space. Perhaps it's not freeing RAM or file handles effectively on very long jobs?

**Comment by ikreymer** [comment]
I think this particular error is caused if there is an empty .warc.gz file, though there may be other underlying issues, perhaps out of disk space? If you could check if there were any empty files if you still have access to this..
