### ISSUE TITLE
Werkzeug 0.14 breaks replay/recording

### ISSUE THREAD

**Issue by rebeccacremona** [ikreymer/pywb#271]
With [Werkzeug 0.14 and 0.14.1](http://werkzeug.pocoo.org/docs/0.14/changes/#version-0-14)

```
{
  "tests/test_auto_colls.py::TestManagedColls::()::test_add_custom_banner_replay[non-frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_add_more_warcs_replay[frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_add_more_warcs_replay[non-frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_add_warcs_replay[frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_add_warcs_replay[non-frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_another_coll_replay[frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_another_coll_replay[non-frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_more_custom_templates_replay[frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_more_custom_templates_replay[non-frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_nested_replay[frame]": true,
  "tests/test_auto_colls.py::TestManagedColls::()::test_nested_replay[non-frame]": true,
  "tests/test_proxy.py::TestRecordingProxy::()::test_proxy_replay_recorded[http]": true,
  "tests/test_proxy.py::TestRecordingProxy::()::test_proxy_replay_recorded[https]": true,
  "tests/test_record_replay.py::TestRecordReplay::()::test_replay_1[frame]": true,
  "tests/test_record_replay.py::TestRecordReplay::()::test_replay_1[non-frame]": true,
  "tests/test_record_replay.py::TestRecordReplay::()::test_replay_2[frame]": true,
  "tests/test_record_replay.py::TestRecordReplay::()::test_replay_2[non-frame]": true,
  "tests/test_record_replay.py::TestRecordReplay::()::test_replay_again_1[frame]": true,
  "tests/test_record_replay.py::TestRecordReplay::()::test_replay_again_1[non-frame]": true
}
.cache/v/cache/lastfailed (END)
```

From the failed tests' stacktraces:
```
File "/Users/rcremona/.virtualenvs/pywb2/lib/python3.6/site-packages/warcio-1.5.1-py3.6.egg/warcio/recordloader.py", line 259, in parse
    raise StatusAndHeadersParserException(msg, parts)
warcio.statusandheaders.StatusAndHeadersParserException: Wrong # of headers, expected arc headers ['WARC-Target-URI', 'WARC-IP-Address', 'WARC-Date', 'Content-Type', 'Content-Length'], Found ['{"modes":', '["list_sources",', '"index",', '"resource"]}']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...<snip>...
  File "/Users/rcremona/.virtualenvs/pywb2/lib/python3.6/site-packages/warcio-1.5.1-py3.6.egg/warcio/recordloader.py", line 215, in _detect_type_load_headers
    raise ArchiveLoadFailed(msg + str(se.statusline))
warcio.recordloader.ArchiveLoadFailed: Unknown archive format, first line: ['{"modes":', '["list_sources",', '"index",', '"resource"]}']
```

Provisionally pinned to 0.13 in https://github.com/ikreymer/pywb/pull/269.

**Comment by ikreymer** [comment]
Thanks! Think I found a fix, just using default matching instead of `path:` in warcserver: https://github.com/ikreymer/pywb/commit/8b6eb6d5ca9eba0f82a9f77c8fb8dbc980c5f4f8
